version: "3.8"

services:
  postgres:
    container_name: postgres
    extends:
      file: backend/docker-compose.yml
      service: postgres

  api:
    container_name: api
    depends_on:
      postgres:
        condition: service_healthy
    extends:
      file: backend/docker-compose.yml
      service: api

  frontend:
    container_name: frontend
    depends_on:
      api:
        condition: service_healthy
    extends:
      file: frontend/docker-compose.yml
      service: webpage